<? if (isset($_['repository'])): ?>

<h1>
    <span class="glyphicon glyphicon-folder-open"></span>&emsp;
    Repository
    <small>
        <?= $_['repository']->getName() ?>
    </small>
</h1>

<?= $this->viewRender('repository/tab.phtml', array(
    'repository' => $_['repository'],
    'active' => 'fields'
)) ?>

<p class="text-right">
    <a href="<?= $this->url('dummy_client.field.create', array(
        'repositoryId' => $_['repository']->getId()
    )) ?>" class="btn btn-success">
        <span class="glyphicon glyphicon-plus"></span>
        Add new field
    </a>
</p>

<? if ($_['fields']->count() == 0): ?>

<p class="alert alert-info">
    <span class="glyphicon glyphicon-info-sign"></span>&emsp;
    No fields yet
</p>

<? else: ?>

<table class="table table-hover table-condensed table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Type</th>
            <th>Label</th>
            <th>Required</th>
            <th>Searchable</th>
            <th>Sortable</th>
            <th>Main</th>
            <th>List</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <? foreach ($_['fields'] as $field): ?>
        <tr>
            <td><?= $field->getDisplayOrder() ?></td>
            <td><?= $field->getName() ?></td>
            <td><?= $field->getType() ?></td>
            <td><?= $field->getLabel() ?></td>
            <td class="col-md-1">
                <? if ($field->getRequired()): ?>
                <span class="glyphicon glyphicon-check"></span>
                <? else: ?>
                <span class="glyphicon glyphicon-unchecked"></span>
                <? endif; ?>
            </td>
            <td class="col-md-1">
                <? if ($field->getSearchable()): ?>
                <span class="glyphicon glyphicon-check"></span>
                <? else: ?>
                <span class="glyphicon glyphicon-unchecked"></span>
                <? endif; ?>
            </td>
            <td class="col-md-1">
                <? if ($field->getSortable()): ?>
                <span class="glyphicon glyphicon-check"></span>
                <? else: ?>
                <span class="glyphicon glyphicon-unchecked"></span>
                <? endif; ?>
            </td>
            <td class="col-md-1">
                <? if ($field->getMain()): ?>
                <span class="glyphicon glyphicon-check"></span>
                <? else: ?>
                <span class="glyphicon glyphicon-unchecked"></span>
                <? endif; ?>
            </td>
            <td class="col-md-1">
                <? if ($field->getList()): ?>
                <span class="glyphicon glyphicon-check"></span>
                <? else: ?>
                <span class="glyphicon glyphicon-unchecked"></span>
                <? endif; ?>
            </td>
            <td class="small col-md-2">
                <a href="<?= $this->url('dummy_client.field.read', array(
                    'id' => $field->getId(),
                    'repositoryId' => $field->getRepositoryId()
                )) ?>">
                    <span class="glyphicon glyphicon-book"></span> read
                </a>
                &emsp;
                <a href="<?= $this->url('dummy_client.field.update', array(
                    'id' => $field->getId(),
                    'repositoryId' => $field->getRepositoryId()
                )) ?>" class="orange">
                    <span class="glyphicon glyphicon-edit"></span> update
                </a>
                &emsp;
                <a href="<?= $this->url('dummy_client.field.delete', array(
                    'id' => $field->getId(),
                    'repositoryId' => $field->getRepositoryId()
                )) ?>" class="red">
                    <span class="glyphicon glyphicon-trash"></span> delete
                </a>
            </td>
        </tr>
        <? endforeach; ?>
    </tbody>
</table>

<? endif; ?>

<? endif; ?>