<?
$items = array(
    array(
        'label' => 'Read',
        'active' => $_['active'] == 'read',
        'icon' => 'book',
        'url' => $this->url('dummy_client.field.read', array(
            'repositoryId' => $_['field']->getRepositoryId(),
            'id' => $_['field']->getId()
        ))
    ),
    array(
        'label' => 'Update',
        'active' => $_['active'] == 'update',
        'icon' => 'edit',
        'url' => $this->url('dummy_client.field.update', array(
            'repositoryId' => $_['field']->getRepositoryId(),
            'id' => $_['field']->getId()
        ))
    ),
    array(
        'label' => 'Delete',
        'active' => $_['active'] == 'delete',
        'icon' => 'trash',
        'url' => $this->url('dummy_client.field.delete', array(
            'repositoryId' => $_['field']->getRepositoryId(),
            'id' => $_['field']->getId()
        ))
    ),
);
?>

<ul class="nav nav-tabs nav-justified" role="tablist">
    <? foreach ($items as $item): ?>
    <li<? if($item['active'] == 'read'): ?> class="active"<? endif; ?>>
        <a href="<?= $item['url'] ?>">
            <span class="glyphicon glyphicon-<?= $item['icon'] ?>"></span>
            <?= $item['label'] ?>
        </a>
    </li>
    <? endforeach; ?>
</ul>

<br />