<?= $this->viewRender('partials/breadcrumbs.phtml') ?>

<? if (isset($_['field']) && isset($_['repository'])): ?>

<h3>
    Repository Field
    <small>
        <?= $_['field']->getName() ?>
    </small>
</h3>

<?= $this->viewRender('repository/field/tab.phtml', array(
    'field' => $_['field'],
    'active' => 'update'
)) ?>

<?= $this->viewRender('partials/form.phtml', array(
    'form' => $_['form']
)) ?>

<? endif; ?>