<? if (isset($_['field']) && isset($_['repository'])): ?>

<h1>
    <span class="glyphicon glyphicon-folder-open"></span>&emsp;
    Repository
    <small>
        <?= $_['repository']->getName() ?>
    </small>
</h1>

<h3>
    Repository Field
    <small>
        <?= $_['field']->getName() ?>
    </small>
</h3>

<?= $this->viewRender('repository/field/tab.phtml', array(
    'field' => $_['field'],
    'active' => 'update'
)) ?>

<?= $this->viewRender('partials/form.phtml', array(
    'form' => $_['form']
)) ?>

<? endif; ?>