<? $navbar = \Michcald\DummyClient\Navbar::getInstance() ?>

<div class="btn-group btn-breadcrumb">
    <a href="<?= $this->url('dummy_client.index.index') ?>" class="btn btn-default">
        <i class="glyphicon glyphicon-home"></i>
    </a>
    <? $i = 1 ?>
    <? foreach ($navbar->getElements() as $element): ?>
    <? $url = $element['url'] ? $element['url'] : '#' ?>
    <? $btn = 'btn-default' ?>
    <? if ($i == count($navbar->getElements())): ?>
    <? $btn = 'btn-info' ?>
    <? endif; ?>
    <? $i++ ?>

    <a href="<?= $url ?>" class="btn <?= $btn ?>">
        <?= $element['label'] ?>
    </a>

    <? endforeach; ?>
</div>

&emsp;