<br />

<div class="container">
    <div class="alert alert-warning">
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th>Method</th>
                    <th>URL</th>
                    <th>Params</th>
                    <th>Status code</th>
                </tr>
            </thead>
            <tbody>
                <? foreach (\Michcald\Mvc\Container::get('dummy_client.rest_client')->getCalls() as $call): ?>
                <tr>
                    <td><?= strtoupper($call['method']) ?></td>
                    <td><?= $call['url'] ?></td>
                    <td><?= json_encode($call['params'])?></td>
                    <td><?= $call['status_code'] ?></td>
                </tr>
                <? endforeach; ?>
            </tbody>
        </table>
    </div>
</div>