<? $session = \Michcald\DummyClient\Session::getInstance()->setNamespace('dummy_client') ?>

<? if (isset($session->flashes)): ?>

<? foreach ($session->flashes as $flash): ?>

<? if (isset($flash['type'])): ?>
    <? if ($flash['type'] == 'success'): ?>
        <? $icon = 'ok-sign' ?>
        <? $class = 'success' ?>
    <? elseif ($flash['type'] == 'error'): ?>
        <? $icon = 'remove-sign' ?>
        <? $class = 'danger' ?>
    <? elseif ($flash['type'] == 'warning'): ?>
        <? $icon = 'warning-sign' ?>
        <? $class = 'warning' ?>
    <? else: ?>
        <? $icon = 'info-sign' ?>
        <? $class = 'info' ?>
    <? endif; ?>
<? else: ?>
    <? $icon = 'info-sign' ?>
    <? $class = 'info' ?>
<? endif; ?>

<p class="alert alert-<?= $class ?>">
    <span class="glyphicon glyphicon-<?= $icon ?>"></span>
    &emsp;
    <?= $flash['message'] ?>
</p>

<? endforeach; ?>

<? unset($session->flashes) ?>

<? endif; ?>