<form role="form" method="<?= $_['form']->getMethod() ?>" enctype="multipart/form-data">
    <? foreach ($_['form']->getElements() as $element): ?>
    <? if ($element->getDisabled() && !$element->getValue()) continue; ?>
    <div class="form-group">

        <? if ($element->getType() != 'hidden'): ?>
        <label for="<?= $element->getName() ?>">
            <?= $element->getLabel() ?>
        </label>
        <? endif; ?>

        <? if ($element->getDescription()): ?>
        <p><small><?= $element->getDescription() ?></small></p>
        <? endif; ?>

        <?= $this->viewRender(sprintf('partials/form/%s.phtml', $element->getType()), array(
            'element' => $element,
            'repository' => isset($_['repository']) ? $_['repository'] : null
        )) ?>

        <? if (count($element->getErrors()) > 0): ?>
        <br />
        <div class="alert alert-danger">
            <ul>
                <? foreach ($element->getErrors() as $error): ?>
                <li><small><?= $error ?></small></li>
                <? endforeach; ?>
            </ul>
        </div>
        <? endif; ?>

    </div>
    <? endforeach; ?>
    <button type="submit" class="btn btn-success">
        <?= $_['form']->getButtonLabel() ?>
    </button>
</form>