<form role="form" method="<?= $_['form']->getMethod() ?>">
    <? foreach ($_['form']->getElements() as $element): ?>
    <? if ($element->getDisabled() && !$element->getValue()) continue; ?>
    <div class="form-group">
        <? if ($element->getType() != 'hidden'): ?>
        <label for="<?= $element->getName() ?>">
            <?= $element->getLabel() ?>
        </label>
        <? endif; ?>
        <?= $this->viewRender(sprintf('partials/form/%s.phtml', $element->getType()), array(
            'element' => $element
        )) ?>
        <? if (count($element->getErrors()) > 0): ?>
        <br />
        <div class="alert alert-danger">
            <ul>
                <? foreach ($element->getErrors() as $error): ?>
                <li><small><?= $error ?></small></li>
                <? endforeach; ?>
            </ul>
        </div>
        <? endif; ?>
    </div>
    <? endforeach; ?>
    <button type="submit" class="btn btn-success">
        <?= $_['form']->getButtonLabel() ?>
    </button>
</form>