<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('dummy_client.index.index') ?>">
                <?= $this->whoami()->getApp()->getTitle() ?>
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <? foreach ($this->whoami()->getReadableRepositories() as $repo): ?>
                <li>
                    <a href="<?= $this->url('dummy_client.entity.index', array(
                        'repositoryId' => $repo->getId()
                    )) ?>">
                        <?= $repo->getPluralLabel() ?>
                    </a>
                </li>
                <? endforeach; ?>
            </ul>
            <? if ($this->whoami()->getApp()->getIsAdmin()): ?>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog white"></span>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li>
                            <a href="<?= $this->url('dummy_client.app.index') ?>">
                                <span class="glyphicon glyphicon-lock"></span>&emsp;
                                Apps
                            </a>
                        </li>
                        <li>
                            <a href="<?= $this->url('dummy_client.repository.index') ?>">
                                <span class="glyphicon glyphicon-folder-open"></span>&emsp;
                                Repositories
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
            <? endif; ?>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>