<? $navbar = \Michcald\DummyClient\Navbar::getInstance() ?>

<ol class="breadcrumb">
    <li>
        <a href="<?= $this->url('dummy_client.index.index') ?>">
            Home
        </a>
    </li>
    <? foreach ($navbar->getElements() as $element): ?>
    <li>
        <? if ($element['url']): ?>
        <a href="<?= $element['url'] ?>">
            <?= $element['label'] ?>
        </a>
        <? else: ?>
        <?= $element['label'] ?>
        <? endif; ?>
    </li>
    <? endforeach; ?>
</ol>