<? $navbar = \Michcald\DummyClient\Navbar::getInstance() ?>

<div class="btn-group btn-breadcrumb">
    <a href="<?= $this->url('dummy_client.index.index') ?>" class="btn btn-default">
        <i class="glyphicon glyphicon-home"></i>
    </a>
    <? foreach ($navbar->getElements() as $element): ?>
    <? if ($element['url']): ?>
    <a href="<?= $element['url'] ?>"  class="btn btn-default">
        <?= $element['label'] ?>
    </a>
    <? else: ?>
    <a href="#" class="btn btn-primary">
        <?= $element['label'] ?>
    </a>
    <? endif; ?>
    <? endforeach; ?>
</div>