routes:
    
    # index
    
    - name: dummy_client.index.index
      methods: ["GET"]
      uri:
          pattern: ~
          requirements: []
      controller: \Michcald\DummyClient\Controller\IndexController
      action: indexAction

    # app
    
    - name: dummy_client.app.index
      methods: ["GET"]
      uri:
          pattern: app/list
          requirements: []
      controller: \Michcald\DummyClient\Controller\AppController
      action: indexAction

    - name: dummy_client.app.create
      methods: ["GET","POST"]
      uri:
          pattern: app/create
          requirements: []
      controller: \Michcald\DummyClient\Controller\AppController
      action: createAction

    - name: dummy_client.app.read
      methods: ["GET"]
      uri:
          pattern: app/{id}/read
          requirements:
              - param: id
                value: \d+
      controller: \Michcald\DummyClient\Controller\AppController
      action: readAction

    - name: dummy_client.app.update
      methods: ["GET","POST"]
      uri:
          pattern: app/{id}/update
          requirements:
              - param: id
                value: \d+
      controller: \Michcald\DummyClient\Controller\AppController
      action: updateAction

    - name: dummy_client.app.delete
      methods: ["GET","POST"]
      uri:
          pattern: app/{id}/delete
          requirements:
              - param: id
                value: \d+
      controller: \Michcald\DummyClient\Controller\AppController
      action: deleteAction
      
    # repository
    
    - name: dummy_client.repository.index
      methods: ["GET"]
      uri:
          pattern: repository/list
          requirements: []
      controller: \Michcald\DummyClient\Controller\RepositoryController
      action: indexAction

    - name: dummy_client.repository.create
      methods: ["GET","POST"]
      uri:
          pattern: repository/create
          requirements: []
      controller: \Michcald\DummyClient\Controller\RepositoryController
      action: createAction

    - name: dummy_client.repository.read
      methods: ["GET"]
      uri:
          pattern: repository/{id}/read
          requirements:
              - param: id
                value: \d+
      controller: \Michcald\DummyClient\Controller\RepositoryController
      action: readAction

    - name: dummy_client.repository.update
      methods: ["GET","POST"]
      uri:
          pattern: repository/{id}/update
          requirements:
              - param: id
                value: \d+
      controller: \Michcald\DummyClient\Controller\RepositoryController
      action: updateAction

    - name: dummy_client.repository.delete
      methods: ["GET","POST"]
      uri:
          pattern: repository/{id}/delete
          requirements:
              - param: id
                value: \d+
      controller: \Michcald\DummyClient\Controller\RepositoryController
      action: deleteAction

    # grants

    - name: dummy_client.grant.index
      methods: ["GET"]
      uri:
          pattern: app/{appId}/grants/list
          requirements:
              - param: appId
                value: \d+
      controller: \Michcald\DummyClient\Controller\GrantController
      action: indexAction

    - name: dummy_client.grant.update
      methods: ["GET"]
      uri:
          pattern: app/{appId}/grant/{id}/{action}
          requirements:
              - param: appId
                value: \d+
              - param: id
                value: \d+
              - param: action
                value: "c|r|u|d"
      controller: \Michcald\DummyClient\Controller\GrantController
      action: updateAction
    
    # default
    
    - name: dummy_client.not_found
      methods: ["GET","POST","PUT","DELETE","OPTIONS","PATCH","HEAD"]
      uri:
          pattern: "{any}"
          requirements:
              - param: any
                value: ".*"
      controller: \Michcald\DummyClient\Controller\IndexController
      action: notFoundAction