<?= $this->viewRender('partials/navbar.phtml', array(
    'urls' => array(
        'Apps' => $this->url('dummy_client.app.index'),
        'Create' => null
    )
)) ?>

<h1>
    <span class="glyphicon glyphicon-lock"></span>
    Create a New App
</h1>

<? if (isset($_['created'])): ?>
<div class="alert alert-success">
    App created successfully
</div>
<? else: ?>

<?= $this->viewRender('partials/form.phtml', array('form' => $_['form'])) ?>

<? endif; ?>