<?= $this->viewRender('partials/navbar.phtml', array(
    'urls' => array(
        'Apps' => $this->url('dummy_client.app.index'),
        'Delete' => null
    )
)) ?>

<?= $this->viewRender('partials/flashes.phtml') ?>

<? if (isset($_['app'])): ?>

<h1>
    <span class="glyphicon glyphicon-lock"></span>
    <?= $_['app']->getName() ?>
</h1>

<?= $this->viewRender('app/tab.phtml', array(
    'app' => $_['app'],
    'active' => 'delete'
)) ?>

<div class="alert alert-danger">
    <p>
        Do you really want to delete this app?
    </p>
    
    <br />
    
    <form role="form" method="post">
        <button type="submit" class="btn btn-danger">
            <span class="glyphicon glyphicon-remove"></span>
            Delete
        </button>
    </form>
    
</div>

<? endif; ?>