<?= $this->viewRender('partials/navbar.phtml', array(
    'urls' => array(
        'Apps' => $this->url('dummy_client.app.index'),
        'Grants' => null
    )
)) ?>

<?= $this->viewRender('partials/flashes.phtml') ?>

<? if (isset($_['app'])): ?>
<h1>
    <span class="glyphicon glyphicon-lock"></span>
    <?= $_['app']->getName() ?>
</h1>

<?= $this->viewRender('app/tab.phtml', array(
    'app' => $_['app'],
    'active' => 'grants'
)) ?>

<? endif; ?>