<ol class="breadcrumb">
    <li>
        <a href="<?= $this->url('dummy_client.index.index') ?>">Home</a>
    </li>
    <li>
        <a href="<?= $this->url('dummy_client.app.index') ?>">Apps</a>
    </li>
    <li>
        <a href="<?= $this->url('dummy_client.app.read', array(
            'id' => $_['app']['id']
        )) ?>">App</a>
    </li>
</ol>

<h1>App</h1>

<?= $this->viewRender('app/tab.phtml', array(
    'app' => $_['app'],
    'active' => 'grants'
)) ?>