<?= $this->viewRender('partials/navbar.phtml', array(
    'urls' => array(
        'Apps' => null
    )
)) ?>

<h1>
    <span class="glyphicon glyphicon-lock"></span>
    Apps
    <small>
        <a href="<?= $this->url('dummy_client.app.create') ?>" class="green">
            <span class="glyphicon glyphicon-plus-sign"></span>
        </a>
    </small>
</h1>

<?= $this->viewRender('partials/flashes.phtml') ?>

<?= $this->viewRender('partials/search.phtml') ?>

<? if ($_['apps']->count() == 0): ?>

<p class="alert alert-info">
    No results yet
</p>

<? else: ?>

<div class="col-md-12">
    <?= $this->viewRender('partials/paginator.phtml', array(
        'paginator' => $_['apps']->getPaginator(),
        'routeId' => 'dummy_client.app.index'
    )) ?>
</div>

<div class="table-responsive">
    <table class="table table-condensed table-hover table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Is Admin</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($_['apps'] as $app): ?>
            <tr>
                <td><?= $app->getId() ?></td>
                <td><?= $app->getName() ?></td>
                <td><?= $app->getDescription() ?></td>
                <td>
                    <? if ($app->getIsAdmin() == 1): ?>
                    Y
                    <? else: ?>
                    N
                    <? endif; ?>
                </td>
                <td class="text-right">
                    <a href="<?= $this->url('dummy_client.app.read', array(
                        'id' => $app->getId()
                    )) ?>">
                        <span class="glyphicon glyphicon-book"></span> read
                    </a>
                    &emsp;
                    <a href="<?= $this->url('dummy_client.app.update', array(
                        'id' => $app->getId()
                    )) ?>" class="orange">
                        <span class="glyphicon glyphicon-edit"></span> update
                    </a>
                    &emsp;
                    <a href="<?= $this->url('dummy_client.app.delete', array(
                        'id' => $app->getId()
                    )) ?>" class="red">
                        <span class="glyphicon glyphicon-trash"></span> delete
                    </a>
                </td>
            </tr>
            <? endforeach; ?>
        </tbody>
    </table>
</div>

<? endif; ?>