<?= $this->viewRender('partials/navbar.phtml', array(
    'urls' => array(
        'Apps' => $this->url('dummy_client.app.index'),
        'Read' => null
    )
)) ?>

<h1>
    <span class="glyphicon glyphicon-lock"></span>
    <?= $_['app']['name'] ?>
</h1>

<?= $this->viewRender('app/tab.phtml', array(
    'app' => $_['app'],
    'active' => 'read'
)) ?>

<?= $this->viewRender('partials/flashes.phtml', array(
    'flashes' => isset($_['_flashes']) ? $_['_flashes'] : array()
)) ?>

<?= $this->viewRender('partials/form-static.phtml', array(
    'form' => $_['form']
)) ?>