<?= $this->viewRender('partials/navbar.phtml', array(
    'urls' => array(
        'Apps' => $this->url('dummy_client.app.index'),
        'Edit' => Null
    )
)) ?>

<h1>
    <span class="glyphicon glyphicon-lock"></span>
    <?= $_['app']['name'] ?>
</h1>

<?= $this->viewRender('app/tab.phtml', array(
    'app' => $_['app'],
    'active' => 'update'
)) ?>

<?= $this->viewRender('partials/form.phtml', array(
    'form' => $_['form']
)) ?>