<h1>
    <span class="glyphicon glyphicon-list"></span>&emsp;
    <?= $_['repository']->getPluralLabel() ?>
    <small>
        <a href="#" class="green">
            <span class="glyphicon glyphicon-plus-sign"></span>
        </a>
    </small>
</h1>

<?//= $this->viewRender('partials/search.phtml') ?>

<? if ($_['entities']->count() == 0): ?>

<p class="alert alert-info">
    No results yet
</p>

<? else: ?>

<div class="col-md-12">
    <?= $this->viewRender('partials/paginator.phtml', array(
        'paginator' => $_['entities']->getPaginator(),
        'routeId' => 'dummy_client.entity.index',
        'routeParams' => array(
            'repositoryId' => $_['repository']->getId()
        )
    )) ?>
</div>

<div class="table-responsive">
    <table class="table table-condensed table-hover table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <? foreach ($_['repositoryFields'] as $field): ?>
                <? if ($field->getList()): ?>
                <th><?= $field->getLabel() ?></th>
                <? endif ?>
                <? endforeach; ?>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($_['entities'] as $entity): ?>
            <? $entityArray = $entity->toArray() ?>
            <tr>
                <td><?= $entity->getId() ?></td>
                <? foreach ($_['repositoryFields'] as $field): ?>
                <? if ($field->getList()): ?>
                <td><?= $entityArray[$field->getName()] ?></td>
                <? endif; ?>
                <? endforeach; ?>
                <td class="text-right">
                    <a href="#">
                        <span class="glyphicon glyphicon-book"></span> read
                    </a>
                    &emsp;
                    <a href="#" class="orange">
                        <span class="glyphicon glyphicon-edit"></span> update
                    </a>
                    &emsp;
                    <a href="#" class="red">
                        <span class="glyphicon glyphicon-trash"></span> delete
                    </a>
                </td>
            </tr>
            <? endforeach; ?>
        </tbody>
    </table>
</div>

<? endif; ?>