<div class="pull-left">
    <?= $this->viewRender('partials/breadcrumbs.phtml') ?>
</div>

<?= $this->viewRender('partials/button/add.phtml', array(
    'url' => $this->url('dummy_client.entity.create', array(
        'repositoryId' => $_['repository']->getId()
    ))
)) ?>

<div class="clearfix"></div>

<?//= $this->viewRender('partials/search.phtml') ?>

<? if ($_['entities']->count() == 0): ?>

<p class="alert alert-info">
    No results yet
</p>

<? else: ?>

<div class="col-md-12">
    <?= $this->viewRender('partials/paginator.phtml', array(
        'paginator' => $_['entities']->getPaginator(),
        'routeId' => 'dummy_client.entity.index',
        'routeParams' => array(
            'repositoryId' => $_['repository']->getId()
        )
    )) ?>
</div>

<div class="table-responsive">
    <table class="table table-condensed table-hover table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <? foreach ($_['repositoryFields'] as $field): ?>
                <? if ($field->getList()): ?>
                <th><?= $field->getLabel() ?></th>
                <? endif ?>
                <? endforeach; ?>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($_['entities'] as $entity): ?>
            <? $entityArray = $entity->toArray() ?>
            <tr>
                <td><?= $entity->getId() ?></td>
                <? foreach ($_['repositoryFields'] as $field): ?>
                <? if ($field->getList()): ?>
                <td>
                    <?= $this->viewRender(sprintf('entity/partials/%s.phtml', $field->getType()), array(
                        'field' => $field,
                        'entity' => $entity,
                        'value' => $entityArray[$field->getName()]
                    )) ?>
                </td>
                <? endif; ?>
                <? endforeach; ?>
                <td class="text-right">
                    <a href="<?= $this->url('dummy_client.entity.read', array(
                        'repositoryId' => $_['repository']->getId(),
                        'id' => $entity->getId()
                    )) ?>">
                        <span class="glyphicon glyphicon-book"></span> read
                    </a>
                    &emsp;
                    <a href="<?= $this->url('dummy_client.entity.update', array(
                        'repositoryId' => $_['repository']->getId(),
                        'id' => $entity->getId()
                    )) ?>" class="orange">
                        <span class="glyphicon glyphicon-edit"></span> update
                    </a>
                    &emsp;
                    <a href="<?= $this->url('dummy_client.entity.delete', array(
                        'repositoryId' => $_['repository']->getId(),
                        'id' => $entity->getId()
                    )) ?>" class="red">
                        <span class="glyphicon glyphicon-trash"></span> delete
                    </a>
                </td>
            </tr>
            <? endforeach; ?>
        </tbody>
    </table>
</div>

<? endif; ?>