<?= $this->viewRender('partials/breadcrumbs.phtml') ?>

<? if (isset($_['entity'])): ?>

<?= $this->viewRender('entity/tab.phtml', array(
    'repository' => $_['repository'],
    'repositoryFields' => $_['repositoryFields'],
    'entity' => $_['entity'],
    'active' => 'update'
)) ?>

<?= $this->viewRender('partials/form.phtml', array(
    'form' => $_['form'],
    'repository' => $_['repository']
)) ?>

<? endif; ?>