<br />

<div class="jumbotron">
    <h1>
        <?= $this->whoami()->getApp()->getName() ?>
        <small>
            <?= $this->whoami()->getApp()->getName() ?>
        </small>
    </h1>
    <p>
        <?= $this->whoami()->getApp()->getDescription() ?>
    </p>
</div>

<? if ($this->whoami()->getApp()->getIsAdmin()): ?>
<ul class="nav nav-pills nav-justified">
    <li>
        <a href="<?= $this->url('dummy_client.app.index') ?>">
            <h2>
                <span class="glyphicon glyphicon-lock"></span>&emsp;
                Apps
            </h2>
        </a>
    </li>
    <li>
        <a href="<?= $this->url('dummy_client.repository.index') ?>">
            <h2>
                <span class="glyphicon glyphicon-folder-open"></span>&emsp;
                Repositories
            </h2>
        </a>
    </li>
</ul>
<? endif; ?>