<br />

<div class="jumbotron">
    <h1>
        <?= $this->config()->title ?>
    </h1>
    <p>
        <?= $this->config()->description ?>
    </p>
    <p><a class="btn btn-primary btn-lg" role="button">Learn more</a></p>
</div>

<ul class="nav nav-pills nav-justified">
    <li>
        <a href="<?= $this->url('dummy_client.app.index') ?>">
            <h2>
                <span class="glyphicon glyphicon-lock"></span>
                Apps
            </h2>
        </a>
    </li>
    <li>
        <a href="<?= $this->url('dummy_client.repository.index') ?>">
            <h2>
                <span class="glyphicon glyphicon-folder-open"></span>
                Repositories
            </h2>
        </a>
    </li>
</ul>