<?= $this->viewRender('partials/breadcrumbs.phtml') ?>

<? if (isset($_['repository'])): ?>

<?= $this->viewRender('repository/tab.phtml', array(
    'repository' => $_['repository'],
    'active' => 'delete'
)) ?>

<div class="alert alert-danger">
    <p>
        Do you really want to delete this repository?
    </p>

    <br />

    <form role="form" method="post">
        <button type="submit" class="btn btn-danger">
            <span class="glyphicon glyphicon-remove"></span>
            Delete
        </button>
    </form>

</div>

<? endif; ?>