<div class="pull-left">
    <?= $this->viewRender('partials/breadcrumbs.phtml') ?>
</div>

<a href="<?= $this->url('dummy_client.repository.create') ?>" class="btn btn-primary">
    <span class="glyphicon glyphicon-plus"></span>
    Add new
</a>

<div class="clearfix"></div>

<?= $this->viewRender('partials/flashes.phtml') ?>

<?//= $this->viewRender('partials/search.phtml') ?>

<? if ($_['repositories']->count() == 0): ?>

<p class="alert alert-info">
    No results yet
</p>

<? else: ?>

<div class="col-md-12">
    <?= $this->viewRender('partials/paginator.phtml', array(
        'paginator' => $_['repositories']->getPaginator(),
        'routeId' => 'dummy_client.repository.index'
    )) ?>
</div>

<div class="table-responsive">
    <table class="table table-condensed table-hover table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($_['repositories'] as $repository): ?>
            <tr>
                <td><?= $repository->getId() ?></td>
                <td><?= $repository->getName() ?></td>
                <td><?= $repository->getDescription() ?></td>
                <td class="text-right small">
                    <a href="<?= $this->url('dummy_client.repository.read', array(
                        'id' => $repository->getId()
                    )) ?>">
                        <span class="glyphicon glyphicon-book"></span> read
                    </a>
                    &emsp;
                    <a href="<?= $this->url('dummy_client.repository.update', array(
                        'id' => $repository->getId()
                    )) ?>" class="orange">
                        <span class="glyphicon glyphicon-edit"></span> update
                    </a>
                    &emsp;
                    <a href="<?= $this->url('dummy_client.repository.delete', array(
                        'id' => $repository->getId()
                    )) ?>" class="red">
                        <span class="glyphicon glyphicon-trash"></span> delete
                    </a>
                </td>
            </tr>
            <? endforeach; ?>
        </tbody>
    </table>
</div>

<? endif; ?>