<ol class="breadcrumb">
    <li>
        <a href="<?= $this->url('dummy_client.index.index') ?>">Home</a>
    </li>
    <li>
        <a href="<?= $this->url('dummy_client.repository.index') ?>">Repositories</a>
    </li>
</ol>

<h1>
    Repositories
    <small>
        <a href="<?= $this->url('dummy_client.repository.create') ?>" class="green">
            <span class="glyphicon glyphicon-plus-sign"></span>
        </a>
    </small>
</h1>

<div class="panel panel-default">
    <div class="panel-body">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search...">
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-search"></span> Search
            </span>
        </div>
    </div>
</div>

<div class="col-md-12">
    <?= $this->viewRender('partials/paginator.phtml', array(
        'paginator' => $_['paginator'],
        'routeId' => 'dummy_client.app.index'
    )) ?>
</div>

<div class="table-responsive">
    <table class="table table-condensed table-hover table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($_['repositories'] as $r): ?>
            <tr>
                <td><?= $r['id'] ?></td>
                <td><?= $r['name'] ?></td>
                <td><?= $r['description'] ?></td>
                <td class="text-right">
                    <a href="<?= $this->url('dummy_client.repository.read', array('name' => $r['name'])) ?>">
                        <span class="glyphicon glyphicon-book"></span> view
                    </a>
                    &emsp;
                    <a href="" class="orange">
                        <span class="glyphicon glyphicon-edit"></span> edit
                    </a>
                    &emsp;
                    <a href="" class="red">
                        <span class="glyphicon glyphicon-remove"></span> delete
                    </a>
                </td>
            </tr>
            <? endforeach; ?>
        </tbody>
    </table>
</div>