<ol class="breadcrumb">
    <li>
        <a href="<?= $this->url('dummy_client.index.index') ?>">Home</a>
    </li>
    <li>
        <a href="<?= $this->url('dummy_client.repository.index') ?>">Repositories</a>
    </li>
    <li>
        <a href="<?= $this->url('dummy_client.repository.read', array(
            'name' => $_['repository']['name']
        )) ?>">Repository</a>
    </li>
</ol>

<h1>Repository</h1>

<?= $this->viewRender('repository/tab.phtml', array(
    'repository' => $_['repository'],
    'active' => 'read'
)) ?>