<? if (isset($_['repository'])): ?>

<h1>
    <span class="glyphicon glyphicon-folder-open"></span>&emsp;
    Repository
    <small>
        <?= $_['repository']->getName() ?>
    </small>
</h1>

<?= $this->viewRender('repository/tab.phtml', array(
    'repository' => $_['repository'],
    'active' => 'update'
)) ?>

<?= $this->viewRender('partials/form.phtml', array(
    'form' => $_['form']
)) ?>

<? endif; ?>