<input
    type="range"
    class="form-control"
    name="<?= $_['element']->getName() ?>"
    id="<?= $_['element']->getName() ?>"
    value="<?= $_['element']->getValue() ?>"

    <? foreach ($_['element']->getOptions() as $attribute => $value): ?>
    <?= $attribute ?>="<?= $value ?>"
    <? endforeach; ?>
    
    />

<div class="col-md-12">
    <div class="text-center" id="<?= $_['element']->getName() ?>_value"></div>
</div>

<script type="text/javascript">
    $(function () {

        $("#<?= $_['element']->getName() ?>_value").text($("#<?= $_['element']->getName() ?>").val());

        $("#<?= $_['element']->getName() ?>").change(function () {
            $("#<?= $_['element']->getName() ?>_value").text($(this).val());
        });
    });
</script>