<select 
    name="<?= $_['element']->getName() ?>"
    id="<?= $_['element']->getName() ?>"
    class="form-control"
    <? if ($_['element']->getDisabled()): ?> disabled<? endif; ?>
    >
    <option value="">-- Select --</option>
    <? foreach ($_['element']->getOptions() as $key => $value): ?>
    <option 
        value="<?= $value?>"
        <? if ((string)$_['element']->getValue() === (string)$value): ?> selected<? endif; ?>
        >
        <?= $key ?>
    </option>
    <? endforeach; ?>
</select>